sudo: false
language: node_js
node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli
  - "./node_modules/bower/bin/bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

notifications:
  webhooks:
    urls:
      secure: "RaVEv4a1Dk75pN5R+0/gfdZleNvw++ojCkwxS1Nrm6hCWLAdfRpDL5QPq/a6iKYu6+HFEt5b37YUIx14Q12L7BhVBtLQhbxEwRV0gD00CcfuxqHENv52vNIVXH0MkENFwW0hE9HaMVXkFho0IvHmSBYNXSQywyP6LhL3fP+Ia+Y="
    on_success: change
    on_failure: always

env:
  global:
  - secure: XFQo+cenYQ3mj3UXr1iJDz6vtN29u/LERtwYYaEUr+iveI0RCs7ztIGedT9NuRY4OSmhQN2xHGlhXR28qeIVtiN9clboJ8yLcdkiml1EIUH5N3FGjPkNEYwYKXSZeUIfl4ciCu86Y4AXJohuaaNIMlIrlUztO5pHH98KYEL0IdA=
  - secure: UYmWzTrim0QYJ4UxLru4tmKBMpgjG1IfW2bFbfIC5mpw+Fxg62eYVvyNtl5JKBwD+Kxk+qFW+5BNzFkuxTUzh1c9fmpUwU0QBCFZXixnVw4zj7EM3hvLvzYCdMsPe4XAxQVCSn7yjykAFr4i9FudVFzC3sh3iB6qK70sXXu4AaE=
